version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fraudshield_db
    environment:
      POSTGRES_DB: fraudshield_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fraudshield_backend
    environment:
      DATABASE_URL: postgresql://postgres:postgrespassword@postgres:5432/fraudshield_db
      SECRET_KEY: fraudshield-production-jwt-key-2026
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: fraudshield_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
